<?php

namespace DigitalArtLabBundle\Entity;

/**
 * checkinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class checkinRepository extends \Doctrine\ORM\EntityRepository
{
}
