<?php

namespace DigitalArtLabBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * checkinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class checkinRepository extends EntityRepository
{
    public function findLastSessions($username)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM DigitalArtLabBundle:checkin c WHERE c.username = :username ORDER BY c.timein DESC'
            )
            ->setParameters(array(
                'username' => $username,
            ))
            ->setMaxResults(20)
            ->getResult();
    }
}
