<?php

namespace DigitalArtLabBundle\Entity;

/**
 * transactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class transactionRepository extends \Doctrine\ORM\EntityRepository
{
    public function groupTransactions()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT z, SUBSTRING(z.time, 1, 10) as date FROM DigitalArtLabBundle:transaction z ORDER BY date'
            )
            ->getResult();
    }

    public function findLastTransactions($username)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM DigitalArtLabBundle:transaction a WHERE a.user = :username ORDER BY a.time DESC'
            )
            ->setParameters(array(
                'username' => $username,
            ))
            ->setMaxResults(10)
            ->getResult();
    }
}
