<?php

namespace DigitalArtLabBundle\Entity;

/**
 * transactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class transactionRepository extends \Doctrine\ORM\EntityRepository
{
    public function groupTransactions()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT z, SUBSTRING(z.time, 1, 10) as date FROM DigitalArtLabBundle:transaction z ORDER BY date'
            )
            ->getResult();
    }
}
